services:
  - type: web
    name: nexus-campus
    env: python
    plan: free
    buildCommand: "python -m pip install -r requirements.txt"
    startCommand: "python server.py"
    envVars:
      - key: ADMIN_PASSWORD
        sync: false
